### ISSUE TITLE
RuntimeError: node.js v14.0.0 or higher is needed to allow compilation of custom models ("conda install nodejs" or follow https://nodejs.org/en/download/)

### ISSUE THREAD

**Issue by AllisonOge** [CorteXlab/cxlb-docker-gnuradio-3.10#1]
This dockerfile cannot serve gr-bokehgui to the browser as I get the following error when I run the simple flowgraph shown

![Screenshot from 2022-10-12 13-08-06](https://user-images.githubusercontent.com/44110875/195338953-7019972c-d079-4647-acdc-6cd1d5ffef64.png)
![Screenshot from 2022-10-12 13-07-52](https://user-images.githubusercontent.com/44110875/195339201-816067c2-7257-4195-9f4b-1dd78629dfb1.png)

The complete console is 
``` shell
<<< Welcome to GNU Radio Companion 3.10.3.0 >>>

Block paths:
	/cortexlab/toolchains/current/share/gnuradio/grc/blocks

Loading: "/root/bokehgui_test/test_bokehgui.grc"
>>> Done

Generating: '/root/bokehgui_test/test_bokehgui.py'

Executing: /usr/bin/python3 -u /root/bokehgui_test/test_bokehgui.py

WARNING:bokeh.server.util:Host wildcard '*' will allow connections originating from multiple (or possibly all) hostnames or IPs. Use non-wildcard values to restrict access explicitly
Please open a browser at the following address: localhost:5007
ERROR:tornado.application:Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:5007', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/usr/local/lib/python3.9/dist-packages/bokeh/server/views/doc_handler.py", line 56, in get
    page = server_html_page_for_session(session,
  File "/usr/local/lib/python3.9/dist-packages/bokeh/embed/server.py", line 255, in server_html_page_for_session
    bundle = bundle_for_objs_and_resources(None, resources)
  File "/usr/local/lib/python3.9/dist-packages/bokeh/embed/bundle.py", line 236, in bundle_for_objs_and_resources
    ext = bundle_models(models)
  File "/usr/local/lib/python3.9/dist-packages/bokeh/util/compiler.py", line 308, in bundle_models
    _bundle_cache[key] = bundle = _bundle_models(custom_models)
  File "/usr/local/lib/python3.9/dist-packages/bokeh/util/compiler.py", line 517, in _bundle_models
    custom_impls = _compile_models(custom_models)
  File "/usr/local/lib/python3.9/dist-packages/bokeh/util/compiler.py", line 494, in _compile_models
    compiled = nodejs_compile(impl.code, lang=impl.lang, file=impl.file)
  File "/usr/local/lib/python3.9/dist-packages/bokeh/util/compiler.py", line 113, in nodejs_compile
    output = _run_nodejs([compilejs_script], dict(code=code, lang=lang, file=file, bokehjs_dir=bokehjs_dir))
  File "/usr/local/lib/python3.9/dist-packages/bokeh/util/compiler.py", line 445, in _run_nodejs
    return _run(_nodejs_path(), argv, input)
  File "/usr/local/lib/python3.9/dist-packages/bokeh/util/compiler.py", line 421, in _nodejs_path
    _nodejs = _detect_nodejs()
  File "/usr/local/lib/python3.9/dist-packages/bokeh/util/compiler.py", line 412, in _detect_nodejs
    raise RuntimeError('node.js v%s or higher is needed to allow compilation of custom models ' % version +
RuntimeError: node.js v14.0.0 or higher is needed to allow compilation of custom models ("conda install nodejs" or follow https://nodejs.org/en/download/)
ERROR:tornado.access:500 GET / (127.0.0.1) 1773.85ms
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 1.49ms
```

The node version installed in the container is `v12.22.5`. I have tried to install a later version that is compatible but to no avail. Please help!

**Comment by mimbert** [comment]
can you provide the flowgraph so that i can reproduce?

**Comment by AllisonOge** [comment]
> can you provide the flowgraph so that i can reproduce?

Yes, I have the flowgraph saved in my repo, [https://github.com/AllisonOge/bokehgui-test](https://github.com/AllisonOge/bokehgui-test).

**Comment by mimbert** [comment]
Thanks for reporting the issue and providing the test case :-)

You can fix the issue in your container by issuing the following commands:
`# apt update && apt full-upgrade`
`# apt -t bookworm install nodejs`

I will update the docker image after I check a few things (updating nodejs to the version in debian bookworm causes the update of core packages like libc6, so I need to quickly check that it doesn't break other things)

**Comment by AllisonOge** [comment]
Thanks @mimbert , it has been resolved. I have v18.7.0 installed

**Comment by mimbert** [comment]
images with gnuradio 3.8 (https://hub.docker.com/repository/docker/m1mbert/cxlb-gnuradio-3.8), 3.9 (https://hub.docker.com/repository/docker/m1mbert/cxlb-gnuradio-3.9) 3.10 (https://hub.docker.com/repository/docker/m1mbert/cxlb-gnuradio-3.10) have been updated

**Comment by AllisonOge** [comment]
> images with gnuradio 3.8 (https://hub.docker.com/repository/docker/m1mbert/cxlb-gnuradio-3.8), 3.9 (https://hub.docker.com/repository/docker/m1mbert/cxlb-gnuradio-3.9) 3.10 (https://hub.docker.com/repository/docker/m1mbert/cxlb-gnuradio-3.10) have been updated

Thanks @mimbert
